### PR TITLE
fix mismatched id between rviz marker and node in pose graph

### PR DESCRIPTION
**Pull request by gene-su**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (add tickets here #1) |
| Primary OS tested on | (Ubuntu, MacOS, Windows) |
| Robotic platform tested on | (Steve's Robot, gazebo simulation of Tally, hardware turtlebot) |

---

## Description of contribution in a few bullet points
* The node selected in Interactive Mode corresponds to the previous node in the pose graph.
Screenshot from 2023-09-25 17-27-03

## Description of documentation updates required from your changes

---

### CODE REVIEW

**Comment by SteveMacenski** [comment]
I'm pretty sure we start numbering from 1 somewhere since `0` is deserved

**Comment by gene-su** [comment]
But when I select ith node in interactive mode, the visualized scan appears to be the scan from the i-1th node. Is this the expected behavior?

**Comment by SteveMacenski** [comment]
Maybe a screen video could be illustrative of before and after :smile:

**Comment by gene-su** [comment]
https://github.com/SteveMacenski/slam_toolbox/assets/47352191/df22be22-5903-4d9e-a40a-1d17505a5d29

**Comment by SteveMacenski** [comment]
Says its corrupt, can't view / download :cry:

**Comment by gene-su** [comment]
Same issue to my mobile device, but it can be viewed on the computer. Additionally, I've uploaded it to YouTube for convenience. [(link)](https://www.youtube.com/watch?v=yNPbavkXaCg)

**Comment by SteveMacenski** [comment]
Ah thank you, that is clear. Thanks for the PR!

**Pull request merged**
