### PR TITLE
Melodic devel-ament_lin_auto

### PR DESCRIPTION
**Pull request by alexx100-cmd**
Follow up to #188

### CODE REVIEW

**Comment by SteveMacenski** [comment]
I dont understand this PR. You're trying to merge melodic devel into eloquent devel on this repo.

**Comment by alexx100-cmd** [comment]
> I dont understand this PR. You're trying to merge melodic devel into eloquent devel on this repo.

I know, i don't have many experience in ROS. I just wanna prove the node on Melodic.
There are other way to build the node in Melodic??

**Comment by SteveMacenski** [comment]
I don't understand this PR, you didn't add anything. You're trying to merge 2 existing separate distribution branches together, what are you trying to accomplish?

**Comment by SteveMacenski** [comment]
Closing PR, please continue discussion in ticket you filed

**Pull request closed without merging**
