### PR TITLE
Remove outdated ceres parameters [melodic] 

### PR DESCRIPTION
**Pull request by PGotzmann**
PR #399 for melodic-devel branch
Fixes Issue #398

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]

**Comment by marcowplm** [comment]
Hi, @PGotzmann and @SteveMacenski I think that this PR is wrong, since the added lines of code are:
```
problem_->SetParameterBlockConstant(&first_node_->second(0));
problem_->SetParameterBlockConstant(&first_node_->second(1));
problem_->SetParameterBlockConstant(&first_node_->second(2));
```

instead of: 
```
problem_->RemoveParameterBlock(&nodeit->second(0));
problem_->RemoveParameterBlock(&nodeit->second(1));
problem_->RemoveParameterBlock(&nodeit->second(2));
```

as correctly suggested in Issue #398 and in the corresponding PR #399 for foxy branch.
The same problem is present in PR #402 for noetic branch.

**Comment by SteveMacenski** [comment]
Agreed @PGotzmann your ROS1 PRs are setting parameter blocks, not removing them. The ROS2 PRs look correct though.

**Comment by SteveMacenski** [comment]
I opened 2 PRs to fix, thanks for pointing that out @marcowplm

**Comment by PGotzmann** [comment]
@SteveMacenski I am sorry for that and thatnks for fixing. Cherry-picking did not work straight out of the box for the ROS1 branches, so I ended up coping the lines to a new commit.  At least that is what I thought I did, but I must have copied the wrong lines instead 😞
@marcowplm thank you for catching that.

**Pull request merged**
