### PR TITLE
Midigate spamming for 50Hz lidar

### PR DESCRIPTION
**Pull request by samiamlabs**
## Basic Info

I'm trying to use Slam Toolbox on a Clearpath Husky with lms111 lidars that default to 50Hz.

Currently, I get a massive amount of info messages about dropped messages in the terminal
```bash
[sync_slam_toolbox_node-15] [INFO] [1661266264.459040162] [slam_toolbox]: Message Filter dropping message: frame 'base_link' at time 5.393 for reason 'discarding message because the queue is full'
[sync_slam_toolbox_node-15] [INFO] [1661266264.499800792] [slam_toolbox]: Message Filter dropping message: frame 'base_link' at time 5.433 for reason 'discarding message because the queue is full'
[sync_slam_toolbox_node-15] [INFO] [1661266264.519281786] [slam_toolbox]: Message Filter dropping message: frame 'base_link' at time 5.453 for reason 'discarding message because the queue is full'
[sync_slam_toolbox_node-15] [INFO] [1661266264.539066862] [slam_toolbox]: Message Filter dropping message: frame 'base_link' at time 5.473 for reason 'discarding message because the queue is full'
[sync_slam_toolbox_node-15] [INFO] [1661266264.559734918] [slam_toolbox]: Message Filter dropping message: frame 'base_link' at time 5.493 for reason 'discarding message because the queue is full'
[sync_slam_toolbox_node-15] [INFO] [1661266264.598413246] [slam_toolbox]: Message Filter dropping message: frame 'base_link' at time 5.534 for reason 'discarding message because the queue is full'
[sync_slam_toolbox_node-15] [INFO] [1661266264.618225423] [slam_toolbox]: Message Filter dropping message: frame 'base_link' at time 5.553 for reason 'discarding message because the queue is full'
[sync_slam_toolbox_node-15] [INFO] [1661266264.638513284] [slam_toolbox]: Message Filter dropping message: frame 'base_link' at time 5.573 for reason 'discarding message because the queue is full'
```
Increasing the queue_size a bit seems to mitigate most of the problem, but maybe there is a better solution.

| ------ | ----------- |
| Primary OS tested on | Ubuntu |
| Robotic platform tested on | gazebo simulation, Clearpath Husky |

---

## Description of contribution in a few bullet points

* Increased queue_size for scan_filter

### CODE REVIEW

**Comment by SteveMacenski** [comment]
We can't blanket make this change unless the choice of 5 is generally principled. Plus, in async mode, we really just want the most recent scan to keeping the buffer would be problematic.  It might be sensible to make this a parameter.

Also, this PR should target `ros2` so that all new distributions have it. Once its merged here, I can backport to Humble.

**Comment by samiamlabs** [comment]
Alright!

I added the queue size as a parameter for now (in case we want to go in that direction) and targeted the PR to `ros2`.

Was thinking about maybe just finding a way to suppress the info log instead of trying to prevent it from dropping messages. The actual mapping seems to be working despite all the logs. 

The logs being INFO rather than DEBUG kind of indicates that you are not supposed to use it that way though...

**Review by SteveMacenski — APPROVED** [review]
LGTM!

**Comment by SteveMacenski** [comment]
I'm planning on doing some syncs across a bunch of repos on Friday, so I'll get these changes out to Humble around then

**Comment by malban** [comment]
I have a related PR open for the tf message filter: https://github.com/ros2/geometry2/pull/544, which seems to struggle with high rate messages.

**Pull request merged**
