### PR TITLE
fix issue (#180) that localization mode may terminate unexpectedly with exception about pthread_mutex_lock

### PR DESCRIPTION
**Pull request by WLwind**
---

## Basic Info

| Info | Please fill out this column |
| ------ | ----------- |
| Ticket(s) this addresses   | (#180) |
| Primary OS tested on | (Ubuntu 20.04 ROS Noetic) |
| Robotic platform tested on | ([Handsfree mini](https://github.com/HANDS-FREE/handsfree)) |

---

## Description of contribution in a few bullet points

* I changed boost::shared_mutex, boost::shared_lock and boost::unique_lock with std::shared_mutex, std::shared_lock and std::unique_lock.
* That unexpected crash never happens to my robot again.

## Description of documentation updates required from your changes

* Change the compile standard from c++11 to c++17.

---
## Future work that may be required in bullet points
* I don't have a ROS2 robot yet. Is anyone there be kind to test this modification on a ROS2 robot?

### CODE REVIEW

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
@WLwind please submit for `ros2` as well

**Comment by SteveMacenski** [comment]
@WLwind I had to revert this, it doesn't compile. Please set the C++17 in the main cmakelists file, the lib karto file only sets to C++17 if not already set, but it is set to 14 in the main file.

**Comment by WLwind** [comment]
> @WLwind I had to revert this, it doesn't compile. Please set the C++17 in the main cmakelists file, the lib karto file only sets to C++17 if not already set, but it is set to 14 in the main file.

The option -std=c++17 has already been set to slam_toolbox/slam_toolbox/CMakeLists.txt before this commit. It compiles well with my computer here.

**Comment by SteveMacenski** [comment]
Got it - if you resubmit the PR to noetic, I'll merge, sorry about that. I saw the issue in ROS2 and assumed I had it consistent across them both

**Pull request merged**
