### PR TITLE
Set HuberLoss as the default ceres_loss_function as suggested in Issue #198

### PR DESCRIPTION
**Pull request by chrisl8**

### CODE REVIEW

**Comment by SteveMacenski** [comment]
@chrisl8 can you submit one for Dashing and Eloquent? They're also actively supported distributions.

**Comment by SteveMacenski** [comment]
https://github.com/SteveMacenski/slam_toolbox/issues/239#issuecomment-667248907

Any input on this? It looks like from benchmarking that this reduces positioning quality

**Comment by chrisl8** [comment]
So many PRs.

Based on the Issues I've seen, and your response, I have no idea if you even think this is a good idea, and even less of my own opinion. It won't hurt my feelings if you reject these. I made them to help out with closing out #198 

If you have some bag files (post links to them) that you want me to run with various configurations, I can probably do it over the weekend, but I'll need some direction:
1. Exact settings to use: `.yaml` file, as well as things like is this sync or async. In fact an exact `.launch` file to use would probably be best.
2. Expected result data and how to obtain it. I can post screen shots of the resulting maps, but I'm not sure how to get the data that #239 is showing.

**Comment by SteveMacenski** [comment]
Maybe the right answer is the following:
- Add a comment on the `None` line that if you have bad odometry / glass / mirror environments, consider using a loss function, but may reduce positioning quality slightly
- Add a new configuration file for a loss-functioned-sync mapping mode
- Add a documentation subsection about this topic to get this information non-tribal and known to all users

That way we don't change default behavior but anyone that really takes a look will see the options. We could link the readme entry to the rplidar ticket where we discussed it

**Comment by chrisl8** [comment]
Adding more information about how and when to use a loss function, and which one to pick, sounds like an excellent idea to me.

If I get time in the next couple of weeks I will submit a PR for my suggested text if you don't want to write it yourself.

**Comment by SteveMacenski** [comment]
OK, I'll leave this PR open since we're discussing it here, but going to kill the rest so that we have 1 discussion point. If you can make the verbage, I can update all the branches if you do this one

**Comment by chrisl8** [comment]
The actual bag file that brought up this issue is the one from #198 . I was able to run that bag file more than a half dozen times with the new code that has since been committed to close that issue and obtained amazing results. with the default settings. Therefor, I am convinced that changes to the ceres_loss_function  are not a good idea for the average user.

@SteveMacenski If there are changes you'd like me to submit for the Readme file, open an issue and tag me in it and I'll make a stab at adding "noob friendly" information to it, but since I'm currently satisfied with my results I need more motivation to do that than I have personally.

**Comment by SteveMacenski** [comment]
Thanks for the note, I think we're all good now that the problem has a real resolution

**Pull request closed without merging**
