### PR TITLE
Allow init from rviz initial pose

### PR DESCRIPTION
**Pull request by Tobias-Fischer**
---
## Description of contribution in a few bullet points

* Added the ability to use the initial pose button in rviz in the online_sync / online_async modes.
* Fixed a crash of rviz when no pose estimate was entered
* This basically allows to easily continue previous mapping sessions

### CODE REVIEW

**Comment by SteveMacenski** [comment]
I don't think this will do what you want. If you don't initialize in the right position from the get-go, you'll have BS scans messing up your map. So if you initialize in a bogus pose and then move the initial pose using this tool, you'll end up really messing up your initial map by at minimum the first laser scan. I don't think that's good behavior.

The way you implemented this seems abusive and there needs to be alot more effort put into safeties for it. I don't have an issue with having a tool drop-pose for setting the initial pose to deserialize from, but it shouldn't be filling in and then executing something like that without permissions.

I think a reasonable alternative would be to have the plugin `/initial_pose` topic automatically fill in the text fields like you did, but then it requires a person to hit the deserialize button, not call that function automatically (what if there's no file listed yet?) What if you're in the middle of mapping a space and you hit that by accident, you'd ruin hours of work potentially.

**Comment by Tobias-Fischer** [comment]
Sure, you've got a point there. I'll modify accordingly on Monday, i.e. not calling DeSerialize automatically.

My use case is deserializing a map, then using the initial pose tool in rviz, and then deserializing again with the given pose, and then continue a previous mapping session. Is this the way to go or is there a better alternative?

**Comment by SteveMacenski** [comment]
> My use case is deserializing a map, then using the initial pose tool in rviz, and then deserializing again with the given pose, and then continue a previous mapping session. Is this the way to go or is there a better alternative?

Not directly, but we could do so indirectly. I imagine for you to set a pose, you need to see a map, so you'll have to deserialize anyhow. But we could make a new service / capability that would have a workflow like:
- Deserialize and show map
- Set initial pose + deserialize in new pose in one interface

Through the rviz plugin, I think the updates you propose make sense. For a more autonomous application, I think a new service would be in order

**Comment by Tobias-Fischer** [comment]
Okay I amended the PR to not deserialize the map automatically.

Shall I open an issue to keep track of the service you propose? I agree that such a service would make sense.

**Review by SteveMacenski — APPROVED** [review]

**Comment by SteveMacenski** [comment]
Please submit an analog to Foxy and I'll merge them both.

This was a really good idea, thanks for proposing it.

**Pull request merged**
