### PR TITLE
adding namespace support for map saving

### PR DESCRIPTION
**Pull request by SteveMacenski**
Per https://github.com/SteveMacenski/slam_toolbox/issues/607

### CODE REVIEW

**Comment by hilary-luo** [comment]
@SteveMacenski Can this fix be merged? Users are continuing to run into this issue.

**Comment by SteveMacenski** [comment]
@hilary-luo I believe I left this asking someone experiencing this issue to test this PR to make sure it resolves their issues (to make sure there aren't other problems afoot as well). If someone tests this for that situation and gives it the thumbs up, I can merge and backport for a release!

Folks commented in https://github.com/SteveMacenski/slam_toolbox/issues/607 but didn't give me an indication that they tested (and then fell off my radar, as most of my work is event-driven)

**Comment by hilary-luo** [comment]
Thanks Steve. @NachtaktiverHalbaffe are you able to test this?

**Comment by NachtaktiverHalbaffe** [comment]
Sorry for the late reply. I'll try to test this when im back at University where my setup is located (Problem occured in my master thesis). Cant give a time estimation because I have to setup a completly new workspace/Docker environment (will be an humble environment because TB4 etc. runs on humble) to seperate everything from the current working setup. Try to get this done this month, have to fulfill some other deadlines for my thesis though and this topic isnt a top priority for my supervisor because he is already satisfied with the current workaround

**Comment by hilary-luo** [comment]
@SteveMacenski This fix worked for me, can we have this merged in? Thanks again

**Comment by SteveMacenski** [comment]
Done

**Pull request merged**
