### PR TITLE
Split packages

### PR DESCRIPTION
**Pull request by LeroyR**
How a package split could be done.

notes:
- should move solver to solver pkg.
- did not test snap/docker generation, unsure where this belongs really
- i dislike the _core pkg name :sweat_smile: 

for #151 [comment](https://github.com/SteveMacenski/slam_toolbox/issues/151#issuecomment-580609553)

### CODE REVIEW

**Comment by SteveMacenski** [comment]
We should slow down and do one thing at a time. First, it looks like from CI this doesn't compile.

Lets focus on one task first. Lets get a PR with just moving out the messages. There's no need for a metapackage here. We just need  slam_toolbox package with the slam_toolbox_msgs as a dependency. The metapackage is usually reserved for situations where there are many packages you need to ship together that might not exist with the same dependency tree. This situation doesn't meet that criteria.

After the msgs package, then we can look at the rviz package

**Comment by LeroyR** [comment]
> We should slow down and do one thing at a time. First, it looks like from CI this doesn't compile.
> 
I did not check installing missed a rule there 

> Lets focus on one task first. Lets get a PR with just moving out the messages.

sure.


> There's no need for a metapackage here. We just need slam_toolbox package with the slam_toolbox_msgs as a dependency. The metapackage is usually reserved for situations where there are many packages you need to ship together that might not exist with the same dependency tree. This situation doesn't meet that criteria.

I did not know that. For example the navigation metapackage seems not to do that.

Here, the metapackage makes sure that installing slam_toolbox includes the same features as before the split, e.g the rviz panel and some solver (if decided to split these away too.)

**Comment by SteveMacenski** [comment]
The navigation metapackage contains packages that are not in the same dependency tree.

Map server and AMCL are not in the dependency tree for `move_base`. Also, navigation was created a long time ago and there are some special considerations for the state of package publication / dependencies back then. 

The RViz plugin actually depends on the slam_toolbox headers, so it probably doesn't need to be abstracted out. Similarly with the ceres plugin. There's nothing stopping someone from creating a plugin outside the slam_toolbox package to work with it. I'd rather not split this into too small of packages. I understand why `msgs` specifically might want to be split up. 

I could see an argument for separating those out, but I think its more of a hassle than its worth, considering it will include headers from the slam_toolbox package. If they were completely independent, that would be a stronger argument.

Any interest in translating these changes to ROS2? 

PS: I also hate the `_core` naming :wink: 

The snap comment: yeah, that may very well break the snap stuff, but frankly, I'd stopped releasing new snaps. I would waste an indeterminate amount of time trying to get the snaps to properly  generate and it just was no longer worth the marginal utility. It can be noted that it was entirely removed in the ROS2 port.

**Review by SteveMacenski — APPROVED** [review]
LGTM

**Comment by LeroyR** [comment]
> The RViz plugin actually depends on the slam_toolbox headers, so it probably doesn't need to be abstracted out. Similarly with the ceres plugin. There's nothing stopping someone from creating a plugin outside the slam_toolbox package to work with it. I'd rather not split this into too small of packages. I understand why `msgs` specifically might want to be split up.

Looking at the header, it only really includes the messages. 
I personally still like to use SLAM **without** having the rviz dependency and all that this pulls in (qt Ogre etc)

> I could see an argument for separating those out, but I think its more of a hassle than its worth, considering it will include headers from the slam_toolbox package. If they were completely independent, that would be a stronger argument.

The argument is practically the same: While we really cant work around the header needs (they are plugins after all, i think dependencies in this direction are fine) some may not want to build/install/deploy all plugins.

> Any interest in translating these changes to ROS2?

As soon as we use ROS2 which could be never :smile: 


> PS: I also hate the `_core` naming 

:man_shrugging: if you do not want a metapkg there is no need to find a name.

PS: Should i push the required changes to split out just the display code?

**Comment by SteveMacenski** [comment]
>  I personally still like to use SLAM without having the rviz dependency and all that this pulls in (qt Ogre etc)

That's fair. 

Lets merge this and in a new PR deal with RVIZ

**Pull request merged**
